---
title: "plots for lexical retrieval project"
output: html_document
---

# packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn=-1)
library(tidyverse) # v1.3.1
library(ggthemes) # v4.2.4
setwd(here::here()) #v1.0.1
```

# drive download

We first download the model log-likelihood file from our public drive folder (see Jupyter notebook for details on how to obtain these model likelihood estimates). We also download the raw data.

```{r}
lexical_data = read.csv(sprintf("https://docs.google.com/uc?id=%s&export=download", '1ssvmD44e2M2kmrEU11utRZ31Lryfj_IC'))

behavioral = read_csv("data/Julie_2021data.csv")
```


# figure 3: prime-based plot
```{r}
primes_data = lexical_data %>% group_by(PrimeCondition, modelType, theta) %>%
  summarise(NLL = sum(NLL), n = n()) %>%
  mutate(k = ifelse(theta == 1.1, 3, ifelse(theta == 1.2, 1, ifelse(theta %in% c(0,1), 2, 4))),
         BIC = k*log(n) -(-2*NLL),
         model = ifelse(modelType == "none", "desc\nonly",
                        ifelse(modelType == "mult", "mult",
          ifelse(theta == 0, "phon\nonly", ifelse(theta == 1, "sem\nonly", 
          ifelse(theta == .1, "add\n.1", ifelse(theta == .2, "add\n.2", 
          ifelse(theta == .3, "add\n.3", ifelse(theta == .4, "add\n.4", 
          ifelse(theta == .5, "add\n.5", ifelse(theta == .6, "add\n.6",
          ifelse(theta == .7, "add\n.7",ifelse(theta == .8, "add\n.8", 
          ifelse(theta == .9, "add\n.9", modelType))))))))))))))


primes_data = primes_data %>% 
  ## rescale unrelated BICs for plotting
  mutate(model = fct_relevel(model, "phon\nonly", "add\n.1","add\n.2","add\n.3","add\n.4",
                             "add\n.5","add\n.6","add\n.7","add\n.8","add\n.9",
                             "sem\nonly", "mult","desc\nonly"),
         PrimeCondition = fct_recode(PrimeCondition, 
                                     phonological = "P", semantic = "R", both = "B", 
                                     unrelated = "U"),
         PrimeCondition = fct_relevel(PrimeCondition, "phonological", "semantic", "both",
                                      "unrelated")) %>%
  rename(prime = PrimeCondition)

sem_range = range(primes_data %>% filter(prime == "semantic") %>% pull(BIC))
phon_range = range(primes_data %>% filter(prime == "phonological") %>% pull(BIC))
both_range = range(primes_data %>% filter(prime == "both") %>% pull(BIC))
unrelated_range = range(primes_data %>% filter(prime == "unrelated") %>% pull(BIC))

colors = c("royalblue4", "darkorange", "darkorchid1", "gold")

## render in 11 x 20

semantic = primes_data %>%
  filter(prime == "semantic")%>%
  ggplot(aes(x = model, y = BIC)) +
  geom_point(data = (primes_data %>%
  filter(prime == "semantic")), size = 2, color = colors[1])+
  geom_line(data = (primes_data %>%
  filter(prime == "semantic" & !model %in% c("mult", "desc\nonly"))),
  group = 1, color = colors[1])+
  geom_bar(data = (primes_data %>%
  filter(prime == "semantic" & model %in% c("mult", "desc\nonly"))), 
  stat = "identity", position = "dodge", width = 0.7, color= "black", fill = colors[1])+
coord_cartesian(ylim = sem_range)+
  theme_few()+
  labs(title = "semantic", x = "")+
    theme(axis.title = element_text(size = rel(2.5)),
          legend.title = element_text(face = "bold", size = rel(2.5)),
         legend.text  = element_text(size = rel(2.5)),
         plot.title = element_text(hjust = .5, size = rel(3)),
         strip.text.x = element_text(size = rel(2.5)),
         axis.text.x = element_text(size = rel(2.5)))

phon = primes_data %>%
  filter(prime == "phonological")%>%
  ggplot(aes(x = model, y = BIC)) +
  geom_point(data = (primes_data %>%
  filter(prime == "phonological")), size = 2, color = colors[2])+
  geom_line(data = (primes_data %>%
  filter(prime == "phonological" & !model %in% c("mult", "desc\nonly"))),
  group = 1, color = colors[2])+
  geom_bar(data = (primes_data %>%
  filter(prime == "phonological" & model %in% c("mult", "desc\nonly"))), 
  stat = "identity", position = "dodge", width = 0.7, color= "black", fill = colors[2])+
coord_cartesian(ylim = phon_range)+
  theme_few()+
  labs(title = "phonological", x = "")+
    theme(axis.title = element_text(size = rel(2.5)),
          legend.title = element_text(face = "bold", size = rel(2.5)),
         legend.text  = element_text(size = rel(2.5)),
         plot.title = element_text(hjust = .5, size = rel(3)),
         strip.text.x = element_text(size = rel(2.5)),
         axis.text.x = element_text(size = rel(2.5)))

both = primes_data %>%
  filter(prime == "both")%>%
  ggplot(aes(x = model, y = BIC)) +
  geom_point(data = (primes_data %>%
  filter(prime == "both")), size = 2, color = colors[3])+
  geom_line(data = (primes_data %>%
  filter(prime == "both" & !model %in% c("mult", "desc\nonly"))),
  group = 1, color = colors[3])+
  geom_bar(data = (primes_data %>%
  filter(prime == "both" & model %in% c("mult", "desc\nonly"))), 
  stat = "identity", position = "dodge", width = 0.7, color= "black", fill = colors[3])+
coord_cartesian(ylim = both_range)+
  theme_few()+
  labs(title = "both", x = "")+
    theme(axis.title = element_text(size = rel(2.5)),
          legend.title = element_text(face = "bold", size = rel(2.5)),
         legend.text  = element_text(size = rel(2.5)),
         plot.title = element_text(hjust = .5, size = rel(3)),
         strip.text.x = element_text(size = rel(2.5)),
         axis.text.x = element_text(size = rel(2.5)))

unrelated = primes_data %>%
  filter(prime == "unrelated")%>%
  ggplot(aes(x = model, y = BIC)) +
  geom_point(data = (primes_data %>%
  filter(prime == "unrelated")), size = 2, color = colors[4])+
  geom_line(data = (primes_data %>%
  filter(prime == "unrelated" & !model %in% c("mult", "desc\nonly"))),
  group = 1, color = colors[4])+
  geom_bar(data = (primes_data %>%
  filter(prime == "unrelated" & model %in% c("mult", "desc\nonly"))), 
  stat = "identity", position = "dodge", width = 0.7, color= "black", fill = colors[4])+
coord_cartesian(ylim = unrelated_range)+
  theme_few()+
  labs(title = "unrelated", x = "model")+
    theme(axis.title = element_text(size = rel(2.5)),
          legend.title = element_text(face = "bold", size = rel(2.5)),
         legend.text  = element_text(size = rel(2.5)),
         plot.title = element_text(hjust = .5, size = rel(3)),
         strip.text.x = element_text(size = rel(2.5)),
         axis.text.x = element_text(size = rel(2.5)))

fig3plot = gridExtra::grid.arrange(semantic, phon, both, unrelated, nrow = 4)
ggsave("plots/fig3plot.pdf", fig3plot, width = 11, height = 20)
```

# figure 4: correct/incorrect plot
```{r}
accuracy_data = lexical_data %>% group_by(NewAccuracy, modelType, theta) %>%
  summarise(NLL = sum(NLL), n = n()) %>%
  mutate(k = ifelse(theta == 1.1, 3, ifelse(theta == 1.2, 1, ifelse(theta %in% c(0,1), 2, 4))),
         BIC = k*log(n) -(-2*NLL),
         model = ifelse(modelType == "none", "desc\nonly",
                        ifelse(modelType == "mult", "mult",
          ifelse(theta == 0, "phon\nonly", ifelse(theta == 1, "sem\nonly", 
          ifelse(theta == .1, "add\n.1", ifelse(theta == .2, "add\n.2", 
          ifelse(theta == .3, "add\n.3", ifelse(theta == .4, "add\n.4", 
          ifelse(theta == .5, "add\n.5", ifelse(theta == .6, "add\n.6",
          ifelse(theta == .7, "add\n.7",ifelse(theta == .8, "add\n.8", 
          ifelse(theta == .9, "add\n.9", modelType))))))))))))))

accuracy_data = accuracy_data %>% 
  mutate(model = fct_relevel(model, "phon\nonly", "add\n.1","add\n.2","add\n.3","add\n.4",
                             "add\n.5","add\n.6","add\n.7","add\n.8","add\n.9",
                             "sem\nonly", "mult","desc\nonly"))

correct_range = range(accuracy_data %>% filter(NewAccuracy == 1) %>% pull(BIC))
incorrect_range = range(accuracy_data %>% filter(NewAccuracy == 0) %>% pull(BIC))

correct = accuracy_data %>%
  filter(NewAccuracy == 1)%>%
  ggplot(aes(x = model, y = BIC)) +
  geom_point(data = (accuracy_data %>%
  filter(NewAccuracy == 1)), size = 2, color = "forestgreen")+
  geom_line(data = (accuracy_data %>%
  filter(NewAccuracy == 1 & !model %in% c("mult", "desc\nonly"))),
  group = 1, color = "forestgreen")+
  geom_bar(data = (accuracy_data %>%
  filter(NewAccuracy == 1 & model %in% c("mult", "desc\nonly"))), 
  stat = "identity", position = "dodge", width = 0.7, color= "black", fill = "forestgreen")+
coord_cartesian(ylim = correct_range)+
  theme_few()+
  labs(title = "correct trials", x = "")+
    theme(axis.title = element_text(size = rel(2.5)),
          legend.title = element_text(face = "bold", size = rel(2.5)),
         legend.text  = element_text(size = rel(2.5)),
         plot.title = element_text(hjust = .5, size = rel(3)),
         strip.text.x = element_text(size = rel(2.5)),
         axis.text.x = element_text(size = rel(2.5)))

incorrect = accuracy_data %>%
  filter(NewAccuracy == 0)%>%
  ggplot(aes(x = model, y = BIC)) +
  geom_point(data = (accuracy_data %>%
  filter(NewAccuracy == 0)), size = 2, color = "darksalmon")+
  geom_line(data = (accuracy_data %>%
  filter(NewAccuracy == 0 & !model %in% c("mult", "desc\nonly"))),
  group = 1, color = "darksalmon")+
  geom_bar(data = (accuracy_data %>%
  filter(NewAccuracy == 0 & model %in% c("mult", "desc\nonly"))), 
  stat = "identity", position = "dodge", width = 0.7, color= "black", fill = "darksalmon")+
coord_cartesian(ylim = incorrect_range)+
  theme_few()+
  labs(title = "incorrect trials", x = "model")+
    theme(axis.title = element_text(size = rel(2.5)),
          legend.title = element_text(face = "bold", size = rel(2.5)),
         legend.text  = element_text(size = rel(2.5)),
         plot.title = element_text(hjust = .5, size = rel(3)),
         strip.text.x = element_text(size = rel(2.5)),
         axis.text.x = element_text(size = rel(2.5)))

fig4plot = gridExtra::grid.arrange(correct, incorrect, nrow = 2)
ggsave("plots/fig4plot.pdf", fig4plot, width = 11, height = 11)

```

# figure 5: states figure

```{r}
states_data = behavioral %>%
  mutate(response = ifelse(NewAccuracy == 1, "correct", 
                           ifelse(Resp == "12345", "no response", "incorrect"))) %>%
  select(Subject, Resp, Target, response, Question.RESP) %>%
  group_by(Question.RESP, response) %>%
  summarise(trials = n()) %>%
  mutate(Question.RESP = factor(Question.RESP))
         

fig5plot = states_data %>%
  rename(state = Question.RESP) %>%
  mutate(state = fct_recode(state, know = "1", `don't know` = "2",
                            `other\nword\nin mind` = "3", `tip of\n tongue` = "4"))%>%
ggplot(aes(x = state, y = trials, group = response, fill = response)) +
      geom_bar(position="stack", stat="identity")+
  theme_few()+
    scale_fill_manual(values = c("forestgreen", "darksalmon", "gray48"))+
  labs( x = "")+
   theme(axis.title = element_text(size = rel(2)),
         legend.position = c(0.8, 0.8),
          legend.title = element_text(face = "bold", size = rel(2)),
         legend.text = element_text( size = rel(2)),
         plot.title = element_text(hjust = .5,size = rel(2.5)),
         axis.text.x = element_text( size = rel(2)))

ggsave("plots/fig5plot.pdf", fig5plot, width = 10, height = 10)
```

# other plots (for poster/talks)

## table 2 plot 

```{r}
table2data = lexical_data %>% group_by(modelType, theta) %>%
  summarise(NLL = sum(NLL), n = n()) %>%
  mutate(k = ifelse(theta == 1.1, 3, ifelse(theta == 1.2, 1, ifelse(theta %in% c(0,1), 2, 4))),
         BIC = k*log(n) -(-2*NLL),
         model = ifelse(modelType == "none", "desc\nonly",
                        ifelse(modelType == "mult", "mult",
          ifelse(theta == 0, "phon\nonly", ifelse(theta == 1, "sem\nonly", 
          ifelse(theta == .1, "add\n.1", ifelse(theta == .2, "add\n.2", 
          ifelse(theta == .3, "add\n.3", ifelse(theta == .4, "add\n.4", 
          ifelse(theta == .5, "add\n.5", ifelse(theta == .6, "add\n.6",
          ifelse(theta == .7, "add\n.7",ifelse(theta == .8, "add\n.8", 
          ifelse(theta == .9, "add\n.9", modelType))))))))))))))


table2data = table2data %>% 
  ## rescale unrelated BICs for plotting
  mutate(model = fct_relevel(model, "phon\nonly", "add\n.1","add\n.2","add\n.3","add\n.4",
                             "add\n.5","add\n.6","add\n.7","add\n.8","add\n.9",
                             "sem\nonly", "mult","desc\nonly"))

table2_range = range(table2data %>% pull(BIC))


colors = c("royalblue4", "darkorange", "darkorchid1", "gold")

## render in 11 x 5

table2plot = table2data %>%
  ggplot(aes(x = model, y = BIC)) +
  geom_point(size = 2, color = colors[1])+
  geom_line(data = (table2data %>%
  filter(!model %in% c("mult", "desc\nonly"))),
  group = 1, color = colors[1])+
  geom_bar(data = (table2data %>%
  filter( model %in% c("mult", "desc\nonly"))), 
  stat = "identity", position = "dodge", width = 0.7, color= "black", fill = colors[1])+
coord_cartesian(ylim = table2_range)+
  theme_few()+
  labs(title = "overall BIC", x = "")+
    theme(axis.title = element_text(size = rel(2.5)),
          legend.title = element_text(face = "bold", size = rel(2.5)),
         legend.text  = element_text(size = rel(2.5)),
         plot.title = element_text(hjust = .5, size = rel(3)),
         strip.text.x = element_text(size = rel(2.5)),
         axis.text.x = element_text(size = rel(2.5)))

table2plot
ggsave("plots/table2plot.pdf", table2plot, width = 11, height = 5)

```

## table 3 plot

```{r}
states_data = lexical_data %>% group_by(Question.RESP, modelType, theta) %>%
  summarise(NLL = sum(NLL), n = n()) %>%
  mutate(k = ifelse(theta == 1.1, 3, ifelse(theta == 1.2, 1, ifelse(theta %in% c(0,1), 2, 4))),
         BIC = k*log(n) -(-2*NLL),
         model = ifelse(modelType == "none", "desc\nonly",
                        ifelse(modelType == "mult", "mult",
          ifelse(theta == 0, "phon\nonly", ifelse(theta == 1, "sem\nonly", 
          ifelse(theta == .1, "add\n.1", ifelse(theta == .2, "add\n.2", 
          ifelse(theta == .3, "add\n.3", ifelse(theta == .4, "add\n.4", 
          ifelse(theta == .5, "add\n.5", ifelse(theta == .6, "add\n.6",
          ifelse(theta == .7, "add\n.7",ifelse(theta == .8, "add\n.8", 
          ifelse(theta == .9, "add\n.9", modelType))))))))))))))

states_data = states_data %>% 
  mutate(model = fct_relevel(model, "phon\nonly", "add\n.1","add\n.2","add\n.3","add\n.4",
                             "add\n.5","add\n.6","add\n.7","add\n.8","add\n.9",
                             "sem\nonly", "mult","desc\nonly"))%>%
  rename(state = Question.RESP) %>%
  mutate(state = as.factor(state))%>%
  mutate(state = fct_recode(state, know = "1", `don't know` = "2",
                            `other\nword\nin mind` = "3", `tip of\n tongue` = "4"))

know_range = range(states_data %>% filter(state == "know") %>% pull(BIC))
dk_range = range(states_data %>% filter(state == "don't know") %>% pull(BIC))
other_range = range(states_data %>% filter(state == "other\nword\nin mind") %>% pull(BIC))
tot_range = range(states_data %>% filter(state == "tip of\n tongue") %>% pull(BIC))

colors = c("darkgreen", "brown", "orange", "purple")

## render in 11 x 20

know = states_data %>%
  filter(state == "know")%>%
  ggplot(aes(x = model, y = BIC)) +
  geom_point(data = (states_data %>%
  filter(state == "know")), size = 2, color = colors[1])+
  geom_line(data = (states_data %>%
  filter(state == "know" & !model %in% c("mult", "desc\nonly"))),
  group = 1, color = colors[1])+
  geom_bar(data = (states_data %>%
  filter(state == "know" & model %in% c("mult", "desc\nonly"))), 
  stat = "identity", position = "dodge", width = 0.7, color= "black", fill = colors[1])+
coord_cartesian(ylim = know_range)+
  theme_few()+
  labs(title = "know", x = "")+
    theme(axis.title = element_text(size = rel(2.5)),
          legend.title = element_text(face = "bold", size = rel(2.5)),
         legend.text  = element_text(size = rel(2.5)),
         plot.title = element_text(hjust = .5, size = rel(3)),
         strip.text.x = element_text(size = rel(2.5)),
         axis.text.x = element_text(size = rel(2.5)))

dontknow = states_data %>%
  filter(state == "don't know")%>%
  ggplot(aes(x = model, y = BIC)) +
  geom_point(data = (states_data %>%
  filter(state == "don't know")), size = 2, color = colors[2])+
  geom_line(data = (states_data %>%
  filter(state == "don't know" & !model %in% c("mult", "desc\nonly"))),
  group = 1, color = colors[2])+
  geom_bar(data = (states_data %>%
  filter(state == "don't know" & model %in% c("mult", "desc\nonly"))), 
  stat = "identity", position = "dodge", width = 0.7, color= "black", fill = colors[2])+
coord_cartesian(ylim = dk_range)+
  theme_few()+
  labs(title = "don't know", x = "")+
    theme(axis.title = element_text(size = rel(2.5)),
          legend.title = element_text(face = "bold", size = rel(2.5)),
         legend.text  = element_text(size = rel(2.5)),
         plot.title = element_text(hjust = .5, size = rel(3)),
         strip.text.x = element_text(size = rel(2.5)),
         axis.text.x = element_text(size = rel(2.5)))

other = states_data %>%
  filter(state == "other\nword\nin mind")%>%
  ggplot(aes(x = model, y = BIC)) +
  geom_point(data = (states_data %>%
  filter(state == "other\nword\nin mind")), size = 2, color = colors[3])+
  geom_line(data = (states_data %>%
  filter(state == "other\nword\nin mind" & !model %in% c("mult", "desc\nonly"))),
  group = 1, color = colors[3])+
  geom_bar(data = (states_data %>%
  filter(state == "other\nword\nin mind" & model %in% c("mult", "desc\nonly"))), 
  stat = "identity", position = "dodge", width = 0.7, color= "black", fill = colors[3])+
coord_cartesian(ylim = other_range)+
  theme_few()+
  labs(title = "other word in mind", x = "")+
    theme(axis.title = element_text(size = rel(2.5)),
          legend.title = element_text(face = "bold", size = rel(2.5)),
         legend.text  = element_text(size = rel(2.5)),
         plot.title = element_text(hjust = .5, size = rel(3)),
         strip.text.x = element_text(size = rel(2.5)),
         axis.text.x = element_text(size = rel(2.5)))

tot = states_data %>%
  filter(state == "tip of\n tongue")%>%
  ggplot(aes(x = model, y = BIC)) +
  geom_point(data = (states_data %>%
  filter(state == "tip of\n tongue")), size = 2, color = colors[4])+
  geom_line(data = (states_data %>%
  filter(state == "tip of\n tongue" & !model %in% c("mult", "desc\nonly"))),
  group = 1, color = colors[4])+
  geom_bar(data = (states_data %>%
  filter(state == "tip of\n tongue" & model %in% c("mult", "desc\nonly"))), 
  stat = "identity", position = "dodge", width = 0.7, color= "black", fill = colors[4])+
coord_cartesian(ylim = tot_range)+
  theme_few()+
  labs(title = "tip of the tongue", x = "")+
    theme(axis.title = element_text(size = rel(2.5)),
          legend.title = element_text(face = "bold", size = rel(2.5)),
         legend.text  = element_text(size = rel(2.5)),
         plot.title = element_text(hjust = .5, size = rel(3)),
         strip.text.x = element_text(size = rel(2.5)),
         axis.text.x = element_text(size = rel(2.5)))

table3plot = gridExtra::grid.arrange(know, dontknow, other, tot, nrow = 4)
ggsave("plots/table3plot.pdf", table3plot, width = 11, height = 20)
```





